Repository chrisnaval/Flex-SPC, pull requests merged in 2018-12, with the labels that each got.

#10 initial data entry with meteor.call and CRUD for user
  .meteor/packages
  .meteor/release
  .meteor/versions
  imports/api/admin/auth/methods.js
  imports/api/admin/auth/server/publications.js
  imports/api/admin/auth/userDetails.js
  imports/api/items/methods.js
  imports/api/parameterConfig/methods.js
  imports/api/parameterConfig/parameterConfig.js
  imports/api/parameterConfig/server/publications.js
  imports/api/parameters/methods.js
  imports/api/parameters/parameters.js
  imports/api/parameters/server/publications.js
  imports/api/products/products.js
  imports/api/products/server/publications.js
  imports/api/users/methods.js
  imports/api/users/server/publications.js
  imports/api/usersDataEntry/methods.js
  imports/startup/client/routes.js
  imports/startup/server/fixtures.js
  imports/startup/server/register-api.js
  imports/ui/components/item/item.html
  imports/ui/components/item/item.js
  imports/ui/components/sample-graph/sample-graph.js
  imports/ui/layouts/headers/home/home-header.html
  imports/ui/layouts/headers/home/home-header.js
  imports/ui/pages/auth/register/register.html
  imports/ui/pages/auth/register/register.js
Labels: api

#15 Task ui 662 customdashboard
  imports/ui/components/admin/create/user-create.html
  imports/ui/components/admin/create/user-create.js
  imports/ui/components/admin/list/user-list.js
  imports/ui/components/admin/update/user-update.html
Labels: ui

#14 fixed issue in user
  imports/api/pages/admin/userProfile/methods.js
  imports/api/pages/admin/userProfile/userProfile.js
Labels: api

#18 structure changes and other modification
  imports/startup/client/admin/routes.js
  imports/ui/components/admin/dashboard/dashboard.html
  imports/ui/components/admin/forms/forms.html
  imports/ui/components/admin/forms/forms.js
  imports/ui/components/admin/forms/forms.less
  imports/ui/components/admin/list/user-list.html
  imports/ui/components/admin/list/user-list.js
  imports/ui/components/admin/update/user-update.html
  imports/ui/components/admin/update/user-update.js
  imports/ui/components/modal/custom-dash/custom.js
  imports/ui/layouts/body/body.js
  imports/ui/layouts/headers/admin/header.html
  imports/ui/layouts/sidebars/admin/sidebar.html
  imports/ui/pages/admin/home/home.js
  imports/ui/pages/admin/users/create/create.html
  imports/ui/pages/admin/users/create/create.js
  imports/ui/pages/admin/users/list/list.html
  imports/ui/pages/admin/users/list/list.js
  imports/ui/pages/admin/users/update/update.html
  imports/ui/pages/admin/users/update/update.js
Labels: ui

#22 restructure for user module in insert method
  imports/api/collections/appModules/appModules.js
  imports/api/collections/appModules/methods.js
  imports/api/collections/configurations/configurations.js
  imports/api/collections/configurations/methods.js
  imports/api/collections/histogramData/histogramData.js
  imports/api/collections/parameterConfig/methods.js
  imports/api/collections/parameterConfig/parameterConfig.js
  imports/api/collections/parameters/methods.js
  imports/api/collections/parameters/parameters.js
  imports/api/collections/perItemTestResults/methods.js
  imports/api/collections/perItemTestResults/perItemTestResults.js
  imports/api/collections/perSampleTestResults/methods.js
  imports/api/collections/perSampleTestResults/perSampleTestResults.js
  imports/api/collections/permissions/methods.js
  imports/api/collections/products/methods.js
  imports/api/collections/products/products.js
  imports/api/collections/rolePermissions/rolePermissions.js
  imports/api/collections/roles/methods.js
  imports/api/collections/roles/roles.js
  imports/api/collections/testers/methods.js
  imports/api/collections/users/methods.js
  imports/api/collections/users/userProfiles.js
  imports/api/pages/configuration/methods.js
  imports/ui/components/admin/forms/forms.html
  imports/ui/components/admin/forms/forms.js
Labels: api

#23 Task ui structure customdashboard
  client/main.less
  imports/startup/client/admin/routes.js
  imports/ui/components/admin/dashboard/dashboard.html
  imports/ui/components/admin/dashboard/dashboard.js
  imports/ui/components/admin/forms/users.html
  imports/ui/components/admin/forms/users.js
  imports/ui/components/admin/forms/users.less
  imports/ui/components/admin/lists/users.html
  imports/ui/components/admin/lists/users.js
  imports/ui/components/admin/lists/users.less
  imports/ui/components/banner/banner.html
  imports/ui/components/dashboard/dashboard.html
  imports/ui/components/dashboard/dashboard.js
  imports/ui/components/dashboard/dashboard.less
  imports/ui/components/graphs/candlestick/candlestick.html
  imports/ui/components/graphs/histograph/histograph.html
  imports/ui/components/graphs/pareto/pareto.html
  imports/ui/components/graphs/range/range.html
  imports/ui/components/graphs/tester/tester.html
  imports/ui/components/graphs/xbar/xbar.html
  imports/ui/components/graphs/yield/yield.html
  imports/ui/components/modal/delete/delete.html
  imports/ui/components/modal/delete/delete.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
  imports/ui/components/modals/modals.less
  imports/ui/layouts/headers/admin/header.js
  imports/ui/layouts/headers/header.html
  imports/ui/layouts/headers/header.less
  imports/ui/layouts/sidebars/admin/sidebar.html
  imports/ui/layouts/sidebars/sidebar.less
  imports/ui/pages/home/home.js
  imports/ui/stylesheets/styles.less
Labels: ui

#24 fixed user and variable
  imports/api/collections/users/methods.js
  imports/ui/components/admin/forms/users.html
  imports/ui/components/admin/forms/users.js
Labels: api

#26 new ui for user list and user create
  client/main.less
  imports/ui/components/admin/forms/users.html
  imports/ui/components/admin/forms/users.js
  imports/ui/components/admin/forms/users.less
  imports/ui/components/admin/lists/users.html
  imports/ui/components/admin/lists/users.less
  imports/ui/components/dashboard/dashboard.js
  imports/ui/components/modals/modals.js
  imports/ui/layouts/headers/admin/header.js
  imports/ui/layouts/headers/header.js
  imports/ui/pages/admin/home/home.html
  imports/ui/pages/auth/login/login.js
  imports/ui/stylesheets/styles.less
Labels: ui

#29 configuration UI
  client/main.less
  imports/startup/client/admin/routes.js
  imports/startup/client/routes.js
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/roles/roles.less
  imports/ui/components/admin/forms/users.less
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/forms/users/users.less
  imports/ui/components/forms/configuration.html
  imports/ui/components/forms/configuration.js
  imports/ui/components/list/product.html
  imports/ui/components/list/product.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
  imports/ui/components/modals/modals.less
  imports/ui/layouts/sidebars/admin/sidebar.html
  imports/ui/layouts/sidebars/sidebar.html
  imports/ui/pages/home/home.html
  imports/ui/stylesheets/styles.less
Labels: ui

#32 configuration integration
  imports/api/collections/configurations/methods.js
  imports/api/collections/users/methods.js
  imports/startup/client/routes.js
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/forms/configuration.html
  imports/ui/components/forms/configuration.js
  imports/ui/components/kanban/kanban.html
  imports/ui/components/kanban/kanban.js
  imports/ui/components/kanban/kanban.less
  imports/ui/components/list/product.html
  imports/ui/components/list/product.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
  imports/ui/pages/configurationTesting/configurationTesting.html
  imports/ui/pages/configurationTesting/configurationTesting.js
  imports/ui/stylesheets/styles.less
Labels: ui

#34 Task ui configuration dataentry
  imports/ui/components/forms/configuration.html
  imports/ui/components/forms/configuration.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
Labels: ui

#35 Connect to MySQL Database with CronJob - Per Minute
  imports/startup/server/index.js
  lib/connect-mysql-db.js
  package-lock.json
  package.json
  server/main.js
Labels: db

#37 additional changes on user
  imports/api/collections/users/methods.js
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/users.html
  imports/ui/components/admin/lists/users.js
  imports/ui/stylesheets/styles.less
Labels: ui

#38 add :function on each function and other modification
  client/main.less
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/users.js
  imports/ui/components/banner/banner.html
  imports/ui/components/banner/banner.js
  imports/ui/components/banner/banner.less
  imports/ui/components/dashboard/dashboard.html
  imports/ui/components/dashboard/dashboard.js
  imports/ui/components/forms/configuration.js
  imports/ui/components/list/product.js
  imports/ui/components/modals/modals.js
  imports/ui/pages/admin/home/home.js
  imports/ui/pages/auth/login/login.js
Labels: ui

#39 update form changes
  imports/ui/components/admin/forms/users/users.html
Labels: ui

#40 additional changes
  imports/ui/components/admin/forms/users/users.js
Labels: ui
