Repository chrisnaval/Flex-SPC, pull requests merged in 2019-01, with the labels that each got.

#43 Refactor and restructure
  imports/api/collections/permissions/methods.js
  imports/api/collections/permissions/permissions.js
  imports/api/collections/rolePermissions/methods.js
  imports/api/collections/roles/methods.js
  imports/api/collections/users/methods.js
  imports/api/collections/users/server/publications.js
  imports/api/collections/users/userProfiles.js
  imports/api/pages/configuration/methods.js
  imports/startup/server/register-api.js
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/users.html
  package.json
Labels: api

#46 Admin Users Module
  imports/api/collections/users/methods.js
  imports/api/collections/users/userProfiles.js
  imports/startup/client/admin/routes.js
  imports/startup/server/fixtures.js
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/users.html
  imports/ui/components/admin/lists/users.js
  imports/ui/layouts/sidebars/admin/sidebar.html
  imports/ui/layouts/sidebars/admin/sidebar.js
Labels: api, ui

#47 logout UI
  client/main.less
  imports/startup/client/admin/routes.js
  imports/ui/layouts/sidebars/admin/sidebar.html
  imports/ui/layouts/sidebars/sidebar.html
  imports/ui/layouts/sidebars/sidebar.less
  imports/ui/pages/auth/auth.less
  imports/ui/stylesheets/styles.less
Labels: ui

#50 roles list
  imports/startup/client/admin/routes.js
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/roles/roles.js
Labels: ui

#53 roles integration
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/admin/lists/users/users.js
  imports/ui/components/forms/configuration.html
  imports/ui/components/forms/configuration.js
  imports/ui/layouts/headers/admin/header.html
  imports/ui/layouts/headers/header.html
Labels: ui

#58 validation for user CRUD
  imports/api/collections/rolePermissions/methods.js
  imports/api/collections/roles/roles.js
  imports/api/collections/users/methods.js
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/forms/users/users.js
  imports/ui/pages/auth/login/login.js
Labels: api

#63 Task ui clickable table view
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/admin/lists/users/users.html
  imports/ui/components/admin/lists/users/users.less
  imports/ui/components/forms/configuration.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
  imports/ui/components/modals/modals.less
  imports/ui/layouts/headers/header.less
  imports/ui/layouts/sidebars/admin/sidebar.html
  imports/ui/layouts/sidebars/admin/sidebar.js
  imports/ui/stylesheets/styles.less
Labels: ui

#64 user view and role view
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/admin/lists/users/users.html
  imports/ui/components/admin/lists/users/users.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
Labels: ui

#65 other modification
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/forms/configuration.html
  imports/ui/components/forms/configuration.js
  imports/ui/components/list/product.html
  imports/ui/components/modals/modals.html
Labels: ui

#67 field replacement
  imports/ui/components/modals/modals.html
Labels: ui

#74 Task ui change password modal
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
  imports/ui/components/modals/modals.less
  imports/ui/layouts/headers/admin/header.html
  imports/ui/layouts/headers/admin/header.js
  imports/ui/layouts/headers/header.html
  imports/ui/layouts/headers/header.js
  imports/ui/layouts/sidebars/admin/sidebar.html
  imports/ui/layouts/sidebars/admin/sidebar.js
  imports/ui/layouts/sidebars/sidebar.html
  imports/ui/layouts/sidebars/sidebar.js
  imports/ui/layouts/sidebars/sidebar.less
  public/img/prof.jpg
  public/img/profile.png
Labels: ui

#78 Task ui change password modal
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/users/users.html
Labels: ui

#80 update for role and permission
  imports/api/collections/rolePermissions/methods.js
  imports/api/collections/roles/roles.js
  imports/api/collections/users/methods.js
Labels: api

#81 Task ui alert message
  client/main.less
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/users/users.html
  imports/ui/components/admin/lists/users/users.js
  imports/ui/components/alert-message/alert-message.html
  imports/ui/components/alert-message/alert-message.js
  imports/ui/components/alert-message/alert-message.less
  imports/ui/components/dashboard/dashboard.html
  imports/ui/components/dashboard/dashboard.js
  imports/ui/components/forms/configuration.html
  imports/ui/components/forms/configuration.js
  imports/ui/components/list/product.html
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
  imports/ui/stylesheets/styles.less
Labels: ui

#86 fixed delete permission
  imports/api/collections/rolePermissions/methods.js
  imports/api/collections/rolePermissions/rolePermissions.js
  imports/api/collections/rolePermissions/server/publications.js
  imports/api/collections/roles/roles.js
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
Labels: api

#87 create, update and delete in form role
  imports/api/collections/rolePermissions/methods.js
  imports/api/collections/rolePermissions/rolePermissions.js
  imports/api/collections/roles/roles.js
  imports/startup/client/admin/routes.js
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/admin/lists/users/users.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
Labels: ui

#89 ingration and fixed error
  imports/api/collections/rolePermissions/methods.js
  imports/api/collections/roles/methods.js
  imports/api/collections/users/methods.js
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/roles/roles.js
Labels: api

#90 read role and update with permissions
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/admin/lists/users/users.html
  imports/ui/components/admin/lists/users/users.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
  imports/ui/stylesheets/styles.less
Labels: ui

#92 fixed bug
  imports/api/collections/rolePermissions/methods.js
  imports/ui/components/admin/lists/users/users.js
Labels: api

#93 modification on creating role
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/admin/lists/users/users.js
  imports/ui/components/modals/modals.html
Labels: ui

#95 read changes to view and some modification on alert messages
  imports/startup/client/admin/routes.js
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/admin/lists/users/users.js
  imports/ui/components/alert-message/alert-message.html
  imports/ui/components/alert-message/alert-message.js
  imports/ui/components/alert-message/alert-message.less
  imports/ui/components/modals/modals.html
  imports/ui/layouts/sidebars/admin/sidebar.js
Labels: ui

#98 Task ui form role integration
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/admin/lists/users/users.html
  imports/ui/components/admin/lists/users/users.js
  imports/ui/components/alert-message/alert-message.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
  imports/ui/stylesheets/styles.less
Labels: ui

#99 Task ui form role integration
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/lists/roles/roles.html
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/graphs/xbar/xbar.js
  imports/ui/components/modals/modals.js
  imports/ui/stylesheets/styles.less
Labels: ui

#102 reset password and fix bug in update role&permission
  imports/api/appModules/admin/roles/methods.js
  imports/ui/components/admin/dashboard/dashboard.html
  imports/ui/components/admin/dashboard/dashboard.js
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/modals/modals.html
  imports/ui/components/modals/modals.js
Labels: api

#105 Task ui form role integration
  client/main.less
  imports/api/collections/users/userProfiles.js
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.html
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/admin/lists/users/users.js
  imports/ui/components/alert-message/alert-message.js
  imports/ui/components/kanban/kanban.html
  imports/ui/components/kanban/kanban.less
  imports/ui/components/modals/modals.html
  imports/ui/stylesheets/styles.less
Labels: ui

#106 configuration
  imports/ui/components/kanban/kanban.html
  imports/ui/components/kanban/kanban.less
  imports/ui/components/lists/configurations/configurations.html
  imports/ui/components/modals/modals.js
  imports/ui/layouts/sidebars/admin/sidebar.html
  imports/ui/layouts/sidebars/admin/sidebar.js
  imports/ui/layouts/sidebars/sidebar.html
  imports/ui/layouts/sidebars/sidebar.js
  imports/ui/layouts/sidebars/sidebar.less
  imports/ui/stylesheets/styles.less
Labels: ui

#107 Task api 484 reports
  .meteor/packages
  .meteor/versions
  imports/api/collections/configurations/configurations.js
  imports/api/collections/configurations/methods.js
  imports/api/collections/configurations/server/publications.js
  imports/ui/components/charts/histogram/histogram.js
  imports/ui/components/forms/configurations/configurations.js
  imports/ui/components/lists/configurations/configurations.js
  imports/ui/pages/reports/reports.html
  imports/ui/pages/reports/reports.js
Labels: api

#108 form role modification and fixed bugs and errors
  imports/ui/components/admin/forms/roles/roles.html
  imports/ui/components/admin/forms/roles/roles.js
  imports/ui/components/admin/forms/users/users.js
  imports/ui/components/admin/lists/roles/roles.js
  imports/ui/components/charts/histogram/histogram.js
Labels: ui
